# -*- coding: utf-8 -*-
"""Task_mongo_CRUD.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OuDg6bEjpOU2NmeZwJWc-f4HubVPYXQ0
"""

import pymongo

# Connecting Mongo Database with Object

db = pymongo.MongoClient("mongodb://kkr016:qwerty12@kkr016-shard-00-00.vrrci.mongodb.net:27017,kkr016-shard-00-01.vrrci.mongodb.net:27017,kkr016-shard-00-02.vrrci.mongodb.net:27017/myFirstDatabase?ssl=true&replicaSet=atlas-k1j4zb-shard-0&authSource=admin&retryWrites=true&w=majority")

db

print("List of Database in MongoDB\n")

k = db.list_database_names()

for i in k:
  print(i)

# Creating A New Collection

col_1=db["telephone_directory"]

print("Create a Directory Which Has Fields Like Name, Phone number, Place etc.,")

t = [
     {"unicode":0, "name":"goku", "mobile":9923457643, "Place":"japan", "age":30, "category":"a"},
     {"unicode":1, "name":"gohan", "mobile":2435356789, "Place":"tokyo", "age":20, "category":"b"},
     {"unicode":2, "name":"goten", "mobile":8765435675, "Place":"tokyo", "age":15, "category":"c"},
     {"unicode":3, "name":"vegeta", "mobile":2387498885, "Place":"hirosima", "age":31, "category":"a"},
     {"unicode":4, "name":"trunks", "mobile":8765727282, "Place":"nagasaki", "age":16, "category":"b"},
     {"unicode":5, "name":"ash", "mobile":92242572567, "Place":"parrot town", "age":18, "category":"c"},
     {"unicode":6, "name":"shinchan", "mobile":5464334666, "Place":"kasukabe", "age":6, "category":"c"},
     {"unicode":7, "name":"stark", "mobile":8827377624, "Place":"newyork", "age":53, "category":"c"},
     {"unicode":8, "name":"steve", "mobile":5444786589, "Place":"queens", "age": 120, "category":"b"},
     {"unicode":9, "name":"thor", "mobile":9876768643, "Place":"asgard", "age":1002, "category":"c"}
     ]

# Creating New Collection

rec_1 = col_1["profile"]

rec_1.insert_many(t)

rec_1.insert_one({"unicode":10, "name":"thanos", "mobile":7876517763, "Place":"chernobyl", "age":1065, "category":"c"})

for i in rec_1.find():
  print(i)

# Query to Find Records Created Above

print("Query to Find The Profile Where Age is Greater Than 18\n")

for i in rec_1.find( {"age":{"$gt":18} }, { '_id':0, "name":1, "age":1, "unicode":1 } ):
  print(i)

print("Query to Find The Profile Where Age is Greater Than 18 and Category is c\n")

for i in rec_1.find( { "$and": [ {"age":{"$gt":18} }, { 'category': 'c' } ] } , { '_id':0 } ):
  print(i)

print("Query to Find The Profile Where Age is Greater Than 18 and Category is \'a\' and also Unicode Lessthan 4\n")

for i in rec_1.find( { "$or": [ { "$and": [ {"age":{"$gt":18} }, { 'category': 'a' } ] }, { "unicode": { "$lt":4} } ] } , { '_id':0 } ):
  print(i)

# Update Queries

query = {"age" : {"$lt":18}}
new_values = {"$set" : {'category' : "c", 'Place' : "India"}}

rec_1.update_one(query, new_values)

for i in rec_1.find( { 'category': 'c' } , { '_id':0 } ):
  print(i)

query = { "$and": [ { "category" : "c" }, {'age': 1002 } ] }
new_values = {"$set" : {'age' : 18}}

rec_1.update_one(query, new_values)

for i in rec_1.find( { 'category': 'c' } , { '_id':0 } ):
  print(i)

# Delete Queries

Query ={'Place': "chernobyl"}

rec_1.delete_one(Query)

for i in rec_1.find( { } , { '_id':0 } ):
  print(i)

Query ={"$and": [ { 'category': "c" }, { 'unicode': 6} ] }

rec_1.delete_one(Query)

for i in rec_1.find():
  print(i)